/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as LoginRouteImport } from './routes/Login'
import { Route as ClientDashboardRouteRouteImport } from './routes/ClientDashboard/route'
import { Route as AdminDashboardRouteRouteImport } from './routes/AdminDashboard/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ClientDashboardIndexRouteImport } from './routes/ClientDashboard/index'
import { Route as ClientDashboardSettingsRouteImport } from './routes/ClientDashboard/Settings'
import { Route as ClientDashboardReviewsRouteImport } from './routes/ClientDashboard/Reviews'
import { Route as ClientDashboardBillingRouteImport } from './routes/ClientDashboard/Billing'
import { Route as ClientDashboardAgentsRouteImport } from './routes/ClientDashboard/Agents'
import { Route as ClientDashboardAccountsRouteImport } from './routes/ClientDashboard/Accounts'
import { Route as AdminDashboardEditiedResponseRouteImport } from './routes/AdminDashboard/EditiedResponse'
import { Route as AdminDashboardDeletedResponseRouteImport } from './routes/AdminDashboard/DeletedResponse'
import { Route as AdminDashboardContentRouteImport } from './routes/AdminDashboard/Content'
import { Route as AdminDashboardClientsRouteImport } from './routes/AdminDashboard/Clients'
import { Route as AdminDashboardAnalyticsRouteImport } from './routes/AdminDashboard/Analytics'
import { Route as AdminDashboardAdminSettingsRouteImport } from './routes/AdminDashboard/AdminSettings'
import { Route as AdminDashboardAdminHomeRouteImport } from './routes/AdminDashboard/AdminHome'

const LoginRoute = LoginRouteImport.update({
  id: '/Login',
  path: '/Login',
  getParentRoute: () => rootRouteImport,
} as any)
const ClientDashboardRouteRoute = ClientDashboardRouteRouteImport.update({
  id: '/ClientDashboard',
  path: '/ClientDashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminDashboardRouteRoute = AdminDashboardRouteRouteImport.update({
  id: '/AdminDashboard',
  path: '/AdminDashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ClientDashboardIndexRoute = ClientDashboardIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => ClientDashboardRouteRoute,
} as any)
const ClientDashboardSettingsRoute = ClientDashboardSettingsRouteImport.update({
  id: '/Settings',
  path: '/Settings',
  getParentRoute: () => ClientDashboardRouteRoute,
} as any)
const ClientDashboardReviewsRoute = ClientDashboardReviewsRouteImport.update({
  id: '/Reviews',
  path: '/Reviews',
  getParentRoute: () => ClientDashboardRouteRoute,
} as any)
const ClientDashboardBillingRoute = ClientDashboardBillingRouteImport.update({
  id: '/Billing',
  path: '/Billing',
  getParentRoute: () => ClientDashboardRouteRoute,
} as any)
const ClientDashboardAgentsRoute = ClientDashboardAgentsRouteImport.update({
  id: '/Agents',
  path: '/Agents',
  getParentRoute: () => ClientDashboardRouteRoute,
} as any)
const ClientDashboardAccountsRoute = ClientDashboardAccountsRouteImport.update({
  id: '/Accounts',
  path: '/Accounts',
  getParentRoute: () => ClientDashboardRouteRoute,
} as any)
const AdminDashboardEditiedResponseRoute =
  AdminDashboardEditiedResponseRouteImport.update({
    id: '/EditiedResponse',
    path: '/EditiedResponse',
    getParentRoute: () => AdminDashboardRouteRoute,
  } as any)
const AdminDashboardDeletedResponseRoute =
  AdminDashboardDeletedResponseRouteImport.update({
    id: '/DeletedResponse',
    path: '/DeletedResponse',
    getParentRoute: () => AdminDashboardRouteRoute,
  } as any)
const AdminDashboardContentRoute = AdminDashboardContentRouteImport.update({
  id: '/Content',
  path: '/Content',
  getParentRoute: () => AdminDashboardRouteRoute,
} as any)
const AdminDashboardClientsRoute = AdminDashboardClientsRouteImport.update({
  id: '/Clients',
  path: '/Clients',
  getParentRoute: () => AdminDashboardRouteRoute,
} as any)
const AdminDashboardAnalyticsRoute = AdminDashboardAnalyticsRouteImport.update({
  id: '/Analytics',
  path: '/Analytics',
  getParentRoute: () => AdminDashboardRouteRoute,
} as any)
const AdminDashboardAdminSettingsRoute =
  AdminDashboardAdminSettingsRouteImport.update({
    id: '/AdminSettings',
    path: '/AdminSettings',
    getParentRoute: () => AdminDashboardRouteRoute,
  } as any)
const AdminDashboardAdminHomeRoute = AdminDashboardAdminHomeRouteImport.update({
  id: '/AdminHome',
  path: '/AdminHome',
  getParentRoute: () => AdminDashboardRouteRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/AdminDashboard': typeof AdminDashboardRouteRouteWithChildren
  '/ClientDashboard': typeof ClientDashboardRouteRouteWithChildren
  '/Login': typeof LoginRoute
  '/AdminDashboard/AdminHome': typeof AdminDashboardAdminHomeRoute
  '/AdminDashboard/AdminSettings': typeof AdminDashboardAdminSettingsRoute
  '/AdminDashboard/Analytics': typeof AdminDashboardAnalyticsRoute
  '/AdminDashboard/Clients': typeof AdminDashboardClientsRoute
  '/AdminDashboard/Content': typeof AdminDashboardContentRoute
  '/AdminDashboard/DeletedResponse': typeof AdminDashboardDeletedResponseRoute
  '/AdminDashboard/EditiedResponse': typeof AdminDashboardEditiedResponseRoute
  '/ClientDashboard/Accounts': typeof ClientDashboardAccountsRoute
  '/ClientDashboard/Agents': typeof ClientDashboardAgentsRoute
  '/ClientDashboard/Billing': typeof ClientDashboardBillingRoute
  '/ClientDashboard/Reviews': typeof ClientDashboardReviewsRoute
  '/ClientDashboard/Settings': typeof ClientDashboardSettingsRoute
  '/ClientDashboard/': typeof ClientDashboardIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/AdminDashboard': typeof AdminDashboardRouteRouteWithChildren
  '/Login': typeof LoginRoute
  '/AdminDashboard/AdminHome': typeof AdminDashboardAdminHomeRoute
  '/AdminDashboard/AdminSettings': typeof AdminDashboardAdminSettingsRoute
  '/AdminDashboard/Analytics': typeof AdminDashboardAnalyticsRoute
  '/AdminDashboard/Clients': typeof AdminDashboardClientsRoute
  '/AdminDashboard/Content': typeof AdminDashboardContentRoute
  '/AdminDashboard/DeletedResponse': typeof AdminDashboardDeletedResponseRoute
  '/AdminDashboard/EditiedResponse': typeof AdminDashboardEditiedResponseRoute
  '/ClientDashboard/Accounts': typeof ClientDashboardAccountsRoute
  '/ClientDashboard/Agents': typeof ClientDashboardAgentsRoute
  '/ClientDashboard/Billing': typeof ClientDashboardBillingRoute
  '/ClientDashboard/Reviews': typeof ClientDashboardReviewsRoute
  '/ClientDashboard/Settings': typeof ClientDashboardSettingsRoute
  '/ClientDashboard': typeof ClientDashboardIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/AdminDashboard': typeof AdminDashboardRouteRouteWithChildren
  '/ClientDashboard': typeof ClientDashboardRouteRouteWithChildren
  '/Login': typeof LoginRoute
  '/AdminDashboard/AdminHome': typeof AdminDashboardAdminHomeRoute
  '/AdminDashboard/AdminSettings': typeof AdminDashboardAdminSettingsRoute
  '/AdminDashboard/Analytics': typeof AdminDashboardAnalyticsRoute
  '/AdminDashboard/Clients': typeof AdminDashboardClientsRoute
  '/AdminDashboard/Content': typeof AdminDashboardContentRoute
  '/AdminDashboard/DeletedResponse': typeof AdminDashboardDeletedResponseRoute
  '/AdminDashboard/EditiedResponse': typeof AdminDashboardEditiedResponseRoute
  '/ClientDashboard/Accounts': typeof ClientDashboardAccountsRoute
  '/ClientDashboard/Agents': typeof ClientDashboardAgentsRoute
  '/ClientDashboard/Billing': typeof ClientDashboardBillingRoute
  '/ClientDashboard/Reviews': typeof ClientDashboardReviewsRoute
  '/ClientDashboard/Settings': typeof ClientDashboardSettingsRoute
  '/ClientDashboard/': typeof ClientDashboardIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/AdminDashboard'
    | '/ClientDashboard'
    | '/Login'
    | '/AdminDashboard/AdminHome'
    | '/AdminDashboard/AdminSettings'
    | '/AdminDashboard/Analytics'
    | '/AdminDashboard/Clients'
    | '/AdminDashboard/Content'
    | '/AdminDashboard/DeletedResponse'
    | '/AdminDashboard/EditiedResponse'
    | '/ClientDashboard/Accounts'
    | '/ClientDashboard/Agents'
    | '/ClientDashboard/Billing'
    | '/ClientDashboard/Reviews'
    | '/ClientDashboard/Settings'
    | '/ClientDashboard/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/AdminDashboard'
    | '/Login'
    | '/AdminDashboard/AdminHome'
    | '/AdminDashboard/AdminSettings'
    | '/AdminDashboard/Analytics'
    | '/AdminDashboard/Clients'
    | '/AdminDashboard/Content'
    | '/AdminDashboard/DeletedResponse'
    | '/AdminDashboard/EditiedResponse'
    | '/ClientDashboard/Accounts'
    | '/ClientDashboard/Agents'
    | '/ClientDashboard/Billing'
    | '/ClientDashboard/Reviews'
    | '/ClientDashboard/Settings'
    | '/ClientDashboard'
  id:
    | '__root__'
    | '/'
    | '/AdminDashboard'
    | '/ClientDashboard'
    | '/Login'
    | '/AdminDashboard/AdminHome'
    | '/AdminDashboard/AdminSettings'
    | '/AdminDashboard/Analytics'
    | '/AdminDashboard/Clients'
    | '/AdminDashboard/Content'
    | '/AdminDashboard/DeletedResponse'
    | '/AdminDashboard/EditiedResponse'
    | '/ClientDashboard/Accounts'
    | '/ClientDashboard/Agents'
    | '/ClientDashboard/Billing'
    | '/ClientDashboard/Reviews'
    | '/ClientDashboard/Settings'
    | '/ClientDashboard/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminDashboardRouteRoute: typeof AdminDashboardRouteRouteWithChildren
  ClientDashboardRouteRoute: typeof ClientDashboardRouteRouteWithChildren
  LoginRoute: typeof LoginRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/Login': {
      id: '/Login'
      path: '/Login'
      fullPath: '/Login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ClientDashboard': {
      id: '/ClientDashboard'
      path: '/ClientDashboard'
      fullPath: '/ClientDashboard'
      preLoaderRoute: typeof ClientDashboardRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/AdminDashboard': {
      id: '/AdminDashboard'
      path: '/AdminDashboard'
      fullPath: '/AdminDashboard'
      preLoaderRoute: typeof AdminDashboardRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ClientDashboard/': {
      id: '/ClientDashboard/'
      path: '/'
      fullPath: '/ClientDashboard/'
      preLoaderRoute: typeof ClientDashboardIndexRouteImport
      parentRoute: typeof ClientDashboardRouteRoute
    }
    '/ClientDashboard/Settings': {
      id: '/ClientDashboard/Settings'
      path: '/Settings'
      fullPath: '/ClientDashboard/Settings'
      preLoaderRoute: typeof ClientDashboardSettingsRouteImport
      parentRoute: typeof ClientDashboardRouteRoute
    }
    '/ClientDashboard/Reviews': {
      id: '/ClientDashboard/Reviews'
      path: '/Reviews'
      fullPath: '/ClientDashboard/Reviews'
      preLoaderRoute: typeof ClientDashboardReviewsRouteImport
      parentRoute: typeof ClientDashboardRouteRoute
    }
    '/ClientDashboard/Billing': {
      id: '/ClientDashboard/Billing'
      path: '/Billing'
      fullPath: '/ClientDashboard/Billing'
      preLoaderRoute: typeof ClientDashboardBillingRouteImport
      parentRoute: typeof ClientDashboardRouteRoute
    }
    '/ClientDashboard/Agents': {
      id: '/ClientDashboard/Agents'
      path: '/Agents'
      fullPath: '/ClientDashboard/Agents'
      preLoaderRoute: typeof ClientDashboardAgentsRouteImport
      parentRoute: typeof ClientDashboardRouteRoute
    }
    '/ClientDashboard/Accounts': {
      id: '/ClientDashboard/Accounts'
      path: '/Accounts'
      fullPath: '/ClientDashboard/Accounts'
      preLoaderRoute: typeof ClientDashboardAccountsRouteImport
      parentRoute: typeof ClientDashboardRouteRoute
    }
    '/AdminDashboard/EditiedResponse': {
      id: '/AdminDashboard/EditiedResponse'
      path: '/EditiedResponse'
      fullPath: '/AdminDashboard/EditiedResponse'
      preLoaderRoute: typeof AdminDashboardEditiedResponseRouteImport
      parentRoute: typeof AdminDashboardRouteRoute
    }
    '/AdminDashboard/DeletedResponse': {
      id: '/AdminDashboard/DeletedResponse'
      path: '/DeletedResponse'
      fullPath: '/AdminDashboard/DeletedResponse'
      preLoaderRoute: typeof AdminDashboardDeletedResponseRouteImport
      parentRoute: typeof AdminDashboardRouteRoute
    }
    '/AdminDashboard/Content': {
      id: '/AdminDashboard/Content'
      path: '/Content'
      fullPath: '/AdminDashboard/Content'
      preLoaderRoute: typeof AdminDashboardContentRouteImport
      parentRoute: typeof AdminDashboardRouteRoute
    }
    '/AdminDashboard/Clients': {
      id: '/AdminDashboard/Clients'
      path: '/Clients'
      fullPath: '/AdminDashboard/Clients'
      preLoaderRoute: typeof AdminDashboardClientsRouteImport
      parentRoute: typeof AdminDashboardRouteRoute
    }
    '/AdminDashboard/Analytics': {
      id: '/AdminDashboard/Analytics'
      path: '/Analytics'
      fullPath: '/AdminDashboard/Analytics'
      preLoaderRoute: typeof AdminDashboardAnalyticsRouteImport
      parentRoute: typeof AdminDashboardRouteRoute
    }
    '/AdminDashboard/AdminSettings': {
      id: '/AdminDashboard/AdminSettings'
      path: '/AdminSettings'
      fullPath: '/AdminDashboard/AdminSettings'
      preLoaderRoute: typeof AdminDashboardAdminSettingsRouteImport
      parentRoute: typeof AdminDashboardRouteRoute
    }
    '/AdminDashboard/AdminHome': {
      id: '/AdminDashboard/AdminHome'
      path: '/AdminHome'
      fullPath: '/AdminDashboard/AdminHome'
      preLoaderRoute: typeof AdminDashboardAdminHomeRouteImport
      parentRoute: typeof AdminDashboardRouteRoute
    }
  }
}

interface AdminDashboardRouteRouteChildren {
  AdminDashboardAdminHomeRoute: typeof AdminDashboardAdminHomeRoute
  AdminDashboardAdminSettingsRoute: typeof AdminDashboardAdminSettingsRoute
  AdminDashboardAnalyticsRoute: typeof AdminDashboardAnalyticsRoute
  AdminDashboardClientsRoute: typeof AdminDashboardClientsRoute
  AdminDashboardContentRoute: typeof AdminDashboardContentRoute
  AdminDashboardDeletedResponseRoute: typeof AdminDashboardDeletedResponseRoute
  AdminDashboardEditiedResponseRoute: typeof AdminDashboardEditiedResponseRoute
}

const AdminDashboardRouteRouteChildren: AdminDashboardRouteRouteChildren = {
  AdminDashboardAdminHomeRoute: AdminDashboardAdminHomeRoute,
  AdminDashboardAdminSettingsRoute: AdminDashboardAdminSettingsRoute,
  AdminDashboardAnalyticsRoute: AdminDashboardAnalyticsRoute,
  AdminDashboardClientsRoute: AdminDashboardClientsRoute,
  AdminDashboardContentRoute: AdminDashboardContentRoute,
  AdminDashboardDeletedResponseRoute: AdminDashboardDeletedResponseRoute,
  AdminDashboardEditiedResponseRoute: AdminDashboardEditiedResponseRoute,
}

const AdminDashboardRouteRouteWithChildren =
  AdminDashboardRouteRoute._addFileChildren(AdminDashboardRouteRouteChildren)

interface ClientDashboardRouteRouteChildren {
  ClientDashboardAccountsRoute: typeof ClientDashboardAccountsRoute
  ClientDashboardAgentsRoute: typeof ClientDashboardAgentsRoute
  ClientDashboardBillingRoute: typeof ClientDashboardBillingRoute
  ClientDashboardReviewsRoute: typeof ClientDashboardReviewsRoute
  ClientDashboardSettingsRoute: typeof ClientDashboardSettingsRoute
  ClientDashboardIndexRoute: typeof ClientDashboardIndexRoute
}

const ClientDashboardRouteRouteChildren: ClientDashboardRouteRouteChildren = {
  ClientDashboardAccountsRoute: ClientDashboardAccountsRoute,
  ClientDashboardAgentsRoute: ClientDashboardAgentsRoute,
  ClientDashboardBillingRoute: ClientDashboardBillingRoute,
  ClientDashboardReviewsRoute: ClientDashboardReviewsRoute,
  ClientDashboardSettingsRoute: ClientDashboardSettingsRoute,
  ClientDashboardIndexRoute: ClientDashboardIndexRoute,
}

const ClientDashboardRouteRouteWithChildren =
  ClientDashboardRouteRoute._addFileChildren(ClientDashboardRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminDashboardRouteRoute: AdminDashboardRouteRouteWithChildren,
  ClientDashboardRouteRoute: ClientDashboardRouteRouteWithChildren,
  LoginRoute: LoginRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
